spring:
  application:
    name: incident-tracker

  datasource:
    url: {SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      jpa-properties:
         hibernate:
           format_sql: true
    # display SQL queries in the console (useful for dev L2/L3)
      update show-sql: true


logging:
  level:
    root: INFO                        # Keep the rest clean
    com.incident.tracker: DEBUG       # Your business code
    org.springframework.web: DEBUG    # HTTP request details
    org.hibernate.SQL: DEBUG          # To see SQL queries


  #spring.datasource.url=$
  #spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
  #spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
  #spring.jpa.hibernate.ddl-auto=update
  # To see SQL queries in the console (useful for dev L2/L3)
  #spring.jpa.show-sql=true